/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.*;
import javax.swing.table.DefaultTableModel;

public final class GlavniProzor extends javax.swing.JFrame {

    int idNumber = 0;
    ControllerPrtljaga controll = new ControllerPrtljaga();

    /**
     * Creates new form GlavniProzor
     */
    public GlavniProzor() {
        initComponents();
        controll.dohvati_evidencijske_listice(tbl_evidencijski_listic, lbSifraEvListica, lbDatum);
        controll.dohvati_racune(tblIzdaniRacuni);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        unos = new javax.swing.JPanel();
        lbSifraEvidencijskogListica = new javax.swing.JLabel();
        lbDatumEvidencijskogListica = new javax.swing.JLabel();
        lbVrstaPrtljage = new javax.swing.JLabel();
        lbCijenaPoDanu = new javax.swing.JLabel();
        lbSifraEvListica = new javax.swing.JLabel();
        lbDatum = new javax.swing.JLabel();
        etVrstaPrtljage = new javax.swing.JTextField();
        cbCijena = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_evidencijski_listic = new javax.swing.JTable();
        btnUnos = new javax.swing.JButton();
        btnBrisi = new javax.swing.JButton();
        provjera_evidencijskog_listica = new javax.swing.JPanel();
        lbUnosEvListica = new javax.swing.JLabel();
        etProvjeraEvListica = new javax.swing.JTextField();
        btnProvjera = new javax.swing.JButton();
        lbSifraEvListica1 = new javax.swing.JLabel();
        lbDatumEvListica = new javax.swing.JLabel();
        lbVrstaPrljage = new javax.swing.JLabel();
        lbCijena = new javax.swing.JLabel();
        sifraEvListica = new javax.swing.JLabel();
        datumEvListica = new javax.swing.JLabel();
        vrstaPrtljage = new javax.swing.JLabel();
        cijenaPoDanu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNoviRacun = new javax.swing.JTable();
        btnDodajStavku = new javax.swing.JButton();
        btnObrisiStavku = new javax.swing.JButton();
        btnPotvrdaStavki = new javax.swing.JButton();
        izdavanje_racuna = new javax.swing.JPanel();
        lbSifraRacuna = new javax.swing.JLabel();
        lbDatumRacuna = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRacun = new javax.swing.JTable();
        lbUkupnaCijenaRacuna = new javax.swing.JLabel();
        cijenaRacuna = new javax.swing.JLabel();
        btnSpremiRacun = new javax.swing.JButton();
        lbRacun = new javax.swing.JLabel();
        lbRacunDatum = new javax.swing.JLabel();
        pregled_racuna = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblIzdaniRacuni = new javax.swing.JTable();
        btnObrisiRacun = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        unos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbSifraEvidencijskogListica.setText("Šifra evidencijskog listića");

        lbDatumEvidencijskogListica.setText("Datum evidencijskog listića");

        lbVrstaPrtljage.setText("Vrsta prtljage");

        lbCijenaPoDanu.setText("Cijena po danu u kunama");

        cbCijena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30", "50", "100", " " }));

        tbl_evidencijski_listic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item 1", "Item 2", "Item3", "Item 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_evidencijski_listic);
        tbl_evidencijski_listic.getAccessibleContext().setAccessibleName("EvidencijskiListic");
        tbl_evidencijski_listic.getAccessibleContext().setAccessibleParent(unos);

        btnUnos.setText("Unos listića");
        btnUnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosActionPerformed(evt);
            }
        });

        btnBrisi.setText("Brisanje listića");
        btnBrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout unosLayout = new javax.swing.GroupLayout(unos);
        unos.setLayout(unosLayout);
        unosLayout.setHorizontalGroup(
            unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(unosLayout.createSequentialGroup()
                        .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(unosLayout.createSequentialGroup()
                                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbVrstaPrtljage)
                                    .addComponent(lbCijenaPoDanu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etVrstaPrtljage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(unosLayout.createSequentialGroup()
                                        .addComponent(cbCijena, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(btnUnos))))
                            .addGroup(unosLayout.createSequentialGroup()
                                .addComponent(lbSifraEvidencijskogListica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)))
                        .addGap(56, 56, 56)
                        .addComponent(btnBrisi)
                        .addGap(581, 581, 581))
                    .addGroup(unosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, unosLayout.createSequentialGroup()
                        .addComponent(lbDatumEvidencijskogListica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSifraEvListica, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(758, 758, 758))))
        );
        unosLayout.setVerticalGroup(
            unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(unosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSifraEvidencijskogListica)
                    .addComponent(lbSifraEvListica))
                .addGap(18, 18, 18)
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDatumEvidencijskogListica)
                    .addComponent(lbDatum))
                .addGap(18, 18, 18)
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etVrstaPrtljage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbVrstaPrtljage))
                .addGap(18, 18, 18)
                .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(unosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCijenaPoDanu)
                        .addComponent(cbCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBrisi))
                    .addComponent(btnUnos))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("unos/brisanje evidencijskog listića", unos);

        lbUnosEvListica.setText("Unesi šifru evidencijskog listića");

        btnProvjera.setText("Provjeri");
        btnProvjera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvjeraActionPerformed(evt);
            }
        });

        lbSifraEvListica1.setText("Šifra evidencijskog listića");

        lbDatumEvListica.setText("Datum evidencijskog listića");

        lbVrstaPrljage.setText("Vrsta prtljage");

        lbCijena.setText("Cijena po danu");

        tblNoviRacun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Šifra listića", "Datum listića", "Vrsta prtljage", "Cijena po danu"
            }
        ));
        jScrollPane2.setViewportView(tblNoviRacun);
        tblNoviRacun.getAccessibleContext().setAccessibleName("");

        btnDodajStavku.setText("Dodaj stavku računa");
        btnDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajStavkuActionPerformed(evt);
            }
        });

        btnObrisiStavku.setText("Briši stavku računa");
        btnObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStavkuActionPerformed(evt);
            }
        });

        btnPotvrdaStavki.setText("Potvrda stavki računa");
        btnPotvrdaStavki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotvrdaStavkiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout provjera_evidencijskog_listicaLayout = new javax.swing.GroupLayout(provjera_evidencijskog_listica);
        provjera_evidencijskog_listica.setLayout(provjera_evidencijskog_listicaLayout);
        provjera_evidencijskog_listicaLayout.setHorizontalGroup(
            provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provjera_evidencijskog_listicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProvjera, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(provjera_evidencijskog_listicaLayout.createSequentialGroup()
                        .addGroup(provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbUnosEvListica)
                            .addComponent(lbSifraEvListica1)
                            .addComponent(lbDatumEvListica)
                            .addComponent(lbVrstaPrljage)
                            .addComponent(lbCijena)
                            .addComponent(btnDodajStavku))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnObrisiStavku)
                            .addGroup(provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(etProvjeraEvListica, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(sifraEvListica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(datumEvListica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vrstaPrtljage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cijenaPoDanu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(btnPotvrdaStavki)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                .addContainerGap(591, Short.MAX_VALUE))
        );
        provjera_evidencijskog_listicaLayout.setVerticalGroup(
            provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provjera_evidencijskog_listicaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUnosEvListica)
                    .addComponent(etProvjeraEvListica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProvjera)
                .addGap(38, 38, 38)
                .addGroup(provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSifraEvListica1)
                    .addComponent(sifraEvListica))
                .addGap(18, 18, 18)
                .addGroup(provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDatumEvListica)
                    .addComponent(datumEvListica))
                .addGap(18, 18, 18)
                .addGroup(provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVrstaPrljage)
                    .addComponent(vrstaPrtljage))
                .addGap(18, 18, 18)
                .addGroup(provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCijena)
                    .addComponent(cijenaPoDanu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(provjera_evidencijskog_listicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajStavku)
                    .addComponent(btnObrisiStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPotvrdaStavki)
                .addGap(250, 250, 250))
        );

        jTabbedPane1.addTab("provjera evidencijskog listića", provjera_evidencijskog_listica);

        lbSifraRacuna.setText("Šifra računa");

        lbDatumRacuna.setText("Datum računa");

        tblRacun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Šifra listića", "Datum listića", "Vrsta prtljage", "Cijena po danu"
            }
        ));
        jScrollPane3.setViewportView(tblRacun);

        lbUkupnaCijenaRacuna.setText("Ukupna cijena računa:");

        cijenaRacuna.setText("0");

        btnSpremiRacun.setText("Spremi račun");
        btnSpremiRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpremiRacunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout izdavanje_racunaLayout = new javax.swing.GroupLayout(izdavanje_racuna);
        izdavanje_racuna.setLayout(izdavanje_racunaLayout);
        izdavanje_racunaLayout.setHorizontalGroup(
            izdavanje_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izdavanje_racunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(izdavanje_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(izdavanje_racunaLayout.createSequentialGroup()
                        .addComponent(lbUkupnaCijenaRacuna)
                        .addGap(18, 18, 18)
                        .addComponent(cijenaRacuna))
                    .addGroup(izdavanje_racunaLayout.createSequentialGroup()
                        .addGroup(izdavanje_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSifraRacuna)
                            .addComponent(lbDatumRacuna))
                        .addGap(18, 18, 18)
                        .addGroup(izdavanje_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbRacun)
                            .addComponent(lbRacunDatum)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpremiRacun))
                .addContainerGap(625, Short.MAX_VALUE))
        );
        izdavanje_racunaLayout.setVerticalGroup(
            izdavanje_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izdavanje_racunaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(izdavanje_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSifraRacuna)
                    .addComponent(lbRacun))
                .addGap(18, 18, 18)
                .addGroup(izdavanje_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDatumRacuna)
                    .addComponent(lbRacunDatum))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(izdavanje_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUkupnaCijenaRacuna)
                    .addComponent(cijenaRacuna))
                .addGap(42, 42, 42)
                .addComponent(btnSpremiRacun)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("izdavanje računa", izdavanje_racuna);

        tblIzdaniRacuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Šifra računa", "Datum i vrijeme računa", "Ukupna cijena računa"
            }
        ));
        jScrollPane4.setViewportView(tblIzdaniRacuni);
        tblIzdaniRacuni.getAccessibleContext().setAccessibleName("Racun");

        btnObrisiRacun.setText("Obriši račun");
        btnObrisiRacun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiRacunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pregled_racunaLayout = new javax.swing.GroupLayout(pregled_racuna);
        pregled_racuna.setLayout(pregled_racunaLayout);
        pregled_racunaLayout.setHorizontalGroup(
            pregled_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregled_racunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pregled_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisiRacun))
                .addContainerGap(707, Short.MAX_VALUE))
        );
        pregled_racunaLayout.setVerticalGroup(
            pregled_racunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pregled_racunaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnObrisiRacun)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("pregled računa", pregled_racuna);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName(getName());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosActionPerformed
        controll.spremanje_evidencijskog_listica(lbSifraEvListica.getText(), lbDatum.getText(), etVrstaPrtljage.getText(), cbCijena.getSelectedItem().toString());
        controll.dohvati_evidencijske_listice(tbl_evidencijski_listic, lbSifraEvListica, lbDatum);
    }//GEN-LAST:event_btnUnosActionPerformed

    private void btnProvjeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvjeraActionPerformed
        controll.potvrda_evidencijskog_listica(sifraEvListica, datumEvListica, vrstaPrtljage, cijenaPoDanu, etProvjeraEvListica.getText());

    }//GEN-LAST:event_btnProvjeraActionPerformed

    private void btnDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajStavkuActionPerformed
        controll.potvrda_stavke(sifraEvListica.getText(), datumEvListica.getText(), vrstaPrtljage.getText(), cijenaPoDanu.getText(), tblNoviRacun, cijenaRacuna);
    }//GEN-LAST:event_btnDodajStavkuActionPerformed

    private void btnPotvrdaStavkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotvrdaStavkiActionPerformed
        controll.kreiranje_racuna(tblNoviRacun, tblRacun, lbRacun, lbRacunDatum, cijenaRacuna);
    }//GEN-LAST:event_btnPotvrdaStavkiActionPerformed

    private void btnSpremiRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpremiRacunActionPerformed
        controll.spremanje_racuna(tblRacun, lbRacun.getText(), lbRacunDatum.getText(), cijenaRacuna);
        controll.dohvati_racune(tblIzdaniRacuni);
    }//GEN-LAST:event_btnSpremiRacunActionPerformed

    private void btnBrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrisiActionPerformed
        idNumber=tbl_evidencijski_listic.getSelectedRow();
        if (idNumber == -1) {
            idNumber = 0;
        }
        ControllerPrtljaga.delete(tbl_evidencijski_listic.getAccessibleContext().getAccessibleName(), (tbl_evidencijski_listic.getValueAt(idNumber, 0)));
        controll.dohvati_evidencijske_listice(tbl_evidencijski_listic, lbSifraEvListica, lbDatum);
    }//GEN-LAST:event_btnBrisiActionPerformed

    private void btnObrisiRacunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiRacunActionPerformed
          idNumber = tblIzdaniRacuni.getSelectedRow();

        if (idNumber == -1) {
            idNumber = 0;
        }
        ControllerPrtljaga.delete(tblIzdaniRacuni.getAccessibleContext().getAccessibleName(), (tblIzdaniRacuni.getValueAt(idNumber, 0)));
        controll.dohvati_racune(tblIzdaniRacuni);
    }//GEN-LAST:event_btnObrisiRacunActionPerformed

    private void btnObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStavkuActionPerformed
       idNumber = tblNoviRacun.getSelectedRow();
        if (idNumber == -1) {
            idNumber = 0;
        }
        DefaultTableModel model = (DefaultTableModel) tblNoviRacun.getModel();
        model.removeRow(idNumber);
       // ControllerPrtljaga.delete(tbl_evidencijski_listic.getAccessibleContext().getAccessibleName(), (tbl_evidencijski_listic.getValueAt(idNumber, 0)));
    }//GEN-LAST:event_btnObrisiStavkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavniProzor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavniProzor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBrisi;
    public javax.swing.JButton btnDodajStavku;
    private javax.swing.JButton btnObrisiRacun;
    public javax.swing.JButton btnObrisiStavku;
    public javax.swing.JButton btnPotvrdaStavki;
    private javax.swing.JButton btnProvjera;
    private javax.swing.JButton btnSpremiRacun;
    public javax.swing.JButton btnUnos;
    public javax.swing.JComboBox<String> cbCijena;
    public javax.swing.JLabel cijenaPoDanu;
    private javax.swing.JLabel cijenaRacuna;
    public javax.swing.JLabel datumEvListica;
    public javax.swing.JTextField etProvjeraEvListica;
    public javax.swing.JTextField etVrstaPrtljage;
    private javax.swing.JPanel izdavanje_racuna;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCijena;
    private javax.swing.JLabel lbCijenaPoDanu;
    public javax.swing.JLabel lbDatum;
    private javax.swing.JLabel lbDatumEvListica;
    private javax.swing.JLabel lbDatumEvidencijskogListica;
    private javax.swing.JLabel lbDatumRacuna;
    private javax.swing.JLabel lbRacun;
    private javax.swing.JLabel lbRacunDatum;
    public javax.swing.JLabel lbSifraEvListica;
    private javax.swing.JLabel lbSifraEvListica1;
    private javax.swing.JLabel lbSifraEvidencijskogListica;
    private javax.swing.JLabel lbSifraRacuna;
    private javax.swing.JLabel lbUkupnaCijenaRacuna;
    private javax.swing.JLabel lbUnosEvListica;
    private javax.swing.JLabel lbVrstaPrljage;
    private javax.swing.JLabel lbVrstaPrtljage;
    private javax.swing.JPanel pregled_racuna;
    private javax.swing.JPanel provjera_evidencijskog_listica;
    public javax.swing.JLabel sifraEvListica;
    private javax.swing.JTable tblIzdaniRacuni;
    public javax.swing.JTable tblNoviRacun;
    private javax.swing.JTable tblRacun;
    public javax.swing.JTable tbl_evidencijski_listic;
    private javax.swing.JPanel unos;
    public javax.swing.JLabel vrstaPrtljage;
    // End of variables declaration//GEN-END:variables

}
