/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mansarda.gradnja;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Matej
 */
public class MansardaGradnjaView extends javax.swing.JFrame {
    
    int idNumber = 0;
    int row;
    int column;
    static Connection con;
    String sqlquery;
    
    public MansardaGradnjaView() {
        initComponents();
        vozila();
        zaposlenici();
        projekti();
        skladiste();
        prihod_trosak();
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mansa = new javax.swing.JTabbedPane();
        Zaposlenici = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_tbl = new javax.swing.JTable();
        z_delete_btn = new javax.swing.JButton();
        z_sort_lbl = new javax.swing.JLabel();
        z_sort_cbox = new javax.swing.JComboBox<>();
        z_find_lbl = new javax.swing.JLabel();
        z_find_txt = new javax.swing.JTextField();
        z_find_btn = new javax.swing.JButton();
        z_cancel_btn = new javax.swing.JButton();
        z_Add_btn = new javax.swing.JButton();
        z_Save_btn = new javax.swing.JButton();
        Vozila = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        vozila_tbl = new javax.swing.JTable();
        V_Add_btn = new javax.swing.JButton();
        v_delete_btn = new javax.swing.JButton();
        V_save_btn = new javax.swing.JButton();
        v_sort_lbl = new javax.swing.JLabel();
        v_sort_cbox = new javax.swing.JComboBox<>();
        v_find_lbl = new javax.swing.JLabel();
        v_find_txt = new javax.swing.JTextField();
        v_find_btn = new javax.swing.JButton();
        Projekti = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        projekti_tbl = new javax.swing.JTable();
        p_cancel_btn = new javax.swing.JButton();
        p_OK_btn = new javax.swing.JButton();
        p_delete_btn = new javax.swing.JButton();
        p_add_btn = new javax.swing.JButton();
        p_sort_lbl1 = new javax.swing.JLabel();
        p_sort_cbox = new javax.swing.JComboBox<>();
        p_find_lbl = new javax.swing.JLabel();
        p_find_txt = new javax.swing.JTextField();
        p_find_btn = new javax.swing.JButton();
        Skladište = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        skladiste_tbl = new javax.swing.JTable();
        s_sort_lbl = new javax.swing.JLabel();
        s_sort_cbox = new javax.swing.JComboBox<>();
        s_find_lbl = new javax.swing.JLabel();
        s_find_txt = new javax.swing.JTextField();
        s_find_btn = new javax.swing.JButton();
        s_save_btn = new javax.swing.JButton();
        s_add_btn = new javax.swing.JButton();
        s_delete_btn = new javax.swing.JButton();
        s_cancel_btn = new javax.swing.JButton();
        Prihod_Trošak = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        prihod_trosak_tbl = new javax.swing.JTable();
        pri_sort_lbl = new javax.swing.JLabel();
        pri_sort_cbox = new javax.swing.JComboBox<>();
        pri_find_lbl = new javax.swing.JLabel();
        pri_find_txt = new javax.swing.JTextField();
        pri_find_btn = new javax.swing.JButton();
        pri_add_btn = new javax.swing.JButton();
        pri_delete_btn = new javax.swing.JButton();
        pri_save_btn = new javax.swing.JButton();
        pri_cancel_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mansarda Gradnja");
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(1024, 720));

        emp_tbl.setAutoCreateRowSorter(true);
        emp_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        emp_tbl.setVerifyInputWhenFocusTarget(false);
        emp_tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emp_tblKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(emp_tbl);
        emp_tbl.getAccessibleContext().setAccessibleName("emp_employees");
        emp_tbl.getAccessibleContext().setAccessibleDescription("");
        emp_tbl.getAccessibleContext().setAccessibleParent(Zaposlenici);

        z_delete_btn.setText("Obriši");
        z_delete_btn.setActionCommand("");
        z_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z_delete_btnActionPerformed(evt);
            }
        });

        z_sort_lbl.setText("Sort by:");

        z_sort_cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z_sort_cboxActionPerformed(evt);
            }
        });

        z_find_lbl.setText("Find:");

        z_find_btn.setText("Search");
        z_find_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z_find_btnActionPerformed(evt);
            }
        });

        z_cancel_btn.setText("Cancel");

        z_Add_btn.setText("Dodaj");
        z_Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z_Add_btnActionPerformed(evt);
            }
        });

        z_Save_btn.setText("Save");
        z_Save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z_Save_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ZaposleniciLayout = new javax.swing.GroupLayout(Zaposlenici);
        Zaposlenici.setLayout(ZaposleniciLayout);
        ZaposleniciLayout.setHorizontalGroup(
            ZaposleniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZaposleniciLayout.createSequentialGroup()
                .addGroup(ZaposleniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(ZaposleniciLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(z_Save_btn)
                        .addGap(18, 18, 18)
                        .addComponent(z_Add_btn)
                        .addGap(18, 18, 18)
                        .addComponent(z_delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(z_cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ZaposleniciLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(ZaposleniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(ZaposleniciLayout.createSequentialGroup()
                                .addComponent(z_sort_lbl)
                                .addGap(18, 18, 18)
                                .addComponent(z_sort_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(z_find_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(z_find_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(z_find_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        ZaposleniciLayout.setVerticalGroup(
            ZaposleniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZaposleniciLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(ZaposleniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(z_sort_lbl)
                    .addGroup(ZaposleniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(z_sort_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(z_find_lbl)
                        .addComponent(z_find_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(z_find_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ZaposleniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(z_delete_btn)
                    .addComponent(z_cancel_btn)
                    .addComponent(z_Add_btn)
                    .addComponent(z_Save_btn))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        Mansa.addTab("Zaposlenici", Zaposlenici);

        vozila_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        vozila_tbl.setCellSelectionEnabled(true);
        vozila_tbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        vozila_tbl.setRowHeight(20);
        vozila_tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(vozila_tbl);
        vozila_tbl.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        vozila_tbl.getAccessibleContext().setAccessibleName("veh_vehicles");
        vozila_tbl.getAccessibleContext().setAccessibleDescription("");
        vozila_tbl.getAccessibleContext().setAccessibleParent(vozila_tbl);

        V_Add_btn.setText("Dodaj");
        V_Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_Add_btnActionPerformed(evt);
            }
        });

        v_delete_btn.setText("Delete");
        v_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_delete_btnActionPerformed(evt);
            }
        });

        V_save_btn.setText("Save");
        V_save_btn.setToolTipText("");
        V_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_save_btnActionPerformed(evt);
            }
        });

        v_sort_lbl.setText("Sortiraj");

        v_sort_cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_sort_cboxActionPerformed(evt);
            }
        });

        v_find_lbl.setText("Traži");

        v_find_txt.setToolTipText("");

        v_find_btn.setText("Traži");
        v_find_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_find_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VozilaLayout = new javax.swing.GroupLayout(Vozila);
        Vozila.setLayout(VozilaLayout);
        VozilaLayout.setHorizontalGroup(
            VozilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VozilaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(VozilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VozilaLayout.createSequentialGroup()
                        .addComponent(v_sort_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(v_sort_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(191, 191, 191)
                        .addComponent(v_find_lbl)
                        .addGap(27, 27, 27)
                        .addComponent(v_find_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(v_find_btn))
                    .addGroup(VozilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(VozilaLayout.createSequentialGroup()
                            .addComponent(V_save_btn)
                            .addGap(18, 18, 18)
                            .addComponent(V_Add_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(v_delete_btn))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        VozilaLayout.setVerticalGroup(
            VozilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VozilaLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(VozilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_sort_lbl)
                    .addComponent(v_sort_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_find_lbl)
                    .addComponent(v_find_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_find_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(VozilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(V_Add_btn)
                    .addComponent(v_delete_btn)
                    .addComponent(V_save_btn))
                .addContainerGap(196, Short.MAX_VALUE))
        );

        Mansa.addTab("Vozila", Vozila);

        projekti_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(projekti_tbl);
        projekti_tbl.getAccessibleContext().setAccessibleName("pro_projects");

        p_cancel_btn.setText("Cancel");

        p_OK_btn.setText("OK");
        p_OK_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_OK_btnActionPerformed(evt);
            }
        });

        p_delete_btn.setText("Obriši");
        p_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_delete_btnActionPerformed(evt);
            }
        });

        p_add_btn.setText("Dodaj");
        p_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_add_btnActionPerformed(evt);
            }
        });

        p_sort_lbl1.setText("Sort by:");

        p_sort_cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_sort_cboxActionPerformed(evt);
            }
        });

        p_find_lbl.setText("Traži");

        p_find_btn.setText("Traži");
        p_find_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_find_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProjektiLayout = new javax.swing.GroupLayout(Projekti);
        Projekti.setLayout(ProjektiLayout);
        ProjektiLayout.setHorizontalGroup(
            ProjektiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjektiLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(ProjektiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProjektiLayout.createSequentialGroup()
                        .addComponent(p_add_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p_delete_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p_OK_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_cancel_btn))
                    .addGroup(ProjektiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ProjektiLayout.createSequentialGroup()
                            .addComponent(p_sort_lbl1)
                            .addGap(18, 18, 18)
                            .addComponent(p_sort_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(179, 179, 179)
                            .addComponent(p_find_lbl)
                            .addGap(18, 18, 18)
                            .addComponent(p_find_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(p_find_btn))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        ProjektiLayout.setVerticalGroup(
            ProjektiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjektiLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(ProjektiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_sort_lbl1)
                    .addComponent(p_sort_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_find_lbl)
                    .addComponent(p_find_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_find_btn))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(ProjektiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_cancel_btn)
                    .addComponent(p_OK_btn)
                    .addComponent(p_delete_btn)
                    .addComponent(p_add_btn))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        Mansa.addTab("Projekti", Projekti);

        skladiste_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(skladiste_tbl);
        skladiste_tbl.getAccessibleContext().setAccessibleName("inv_warehouse");
        skladiste_tbl.getAccessibleContext().setAccessibleDescription("");

        s_sort_lbl.setText("Sortiraj :");

        s_sort_cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_sort_cboxActionPerformed(evt);
            }
        });

        s_find_lbl.setText("Traži: ");

        s_find_btn.setText("Traži");
        s_find_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_find_btnActionPerformed(evt);
            }
        });

        s_save_btn.setText("Spremi");
        s_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_save_btnActionPerformed(evt);
            }
        });

        s_add_btn.setText("Dodaj");
        s_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_add_btnActionPerformed(evt);
            }
        });

        s_delete_btn.setText("Obriši");
        s_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_delete_btnActionPerformed(evt);
            }
        });

        s_cancel_btn.setText("Cancel");
        s_cancel_btn.setToolTipText("");
        s_cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SkladišteLayout = new javax.swing.GroupLayout(Skladište);
        Skladište.setLayout(SkladišteLayout);
        SkladišteLayout.setHorizontalGroup(
            SkladišteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SkladišteLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(SkladišteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SkladišteLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SkladišteLayout.createSequentialGroup()
                        .addComponent(s_sort_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(s_sort_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(s_find_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s_find_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s_find_btn)
                        .addGap(79, 79, 79))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SkladišteLayout.createSequentialGroup()
                .addGap(503, 503, 503)
                .addComponent(s_add_btn)
                .addGap(18, 18, 18)
                .addComponent(s_delete_btn)
                .addGap(11, 11, 11)
                .addComponent(s_save_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(s_cancel_btn)
                .addGap(89, 89, 89))
        );
        SkladišteLayout.setVerticalGroup(
            SkladišteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SkladišteLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(SkladišteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s_sort_lbl)
                    .addComponent(s_sort_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_find_lbl)
                    .addComponent(s_find_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s_find_btn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(SkladišteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s_add_btn)
                    .addComponent(s_delete_btn)
                    .addComponent(s_cancel_btn)
                    .addComponent(s_save_btn))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        Mansa.addTab("Skladište", Skladište);

        prihod_trosak_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(prihod_trosak_tbl);
        prihod_trosak_tbl.getAccessibleContext().setAccessibleName("cli_clients");

        pri_sort_lbl.setText("Sortiraj :");

        pri_sort_cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pri_sort_cboxActionPerformed(evt);
            }
        });

        pri_find_lbl.setText("Traži: ");

        pri_find_btn.setText("Traži");
        pri_find_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pri_find_btnActionPerformed(evt);
            }
        });

        pri_add_btn.setText("Dodaj");
        pri_add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pri_add_btnActionPerformed(evt);
            }
        });

        pri_delete_btn.setText("Obriši");
        pri_delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pri_delete_btnActionPerformed(evt);
            }
        });

        pri_save_btn.setText("Spremi");
        pri_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pri_save_btnActionPerformed(evt);
            }
        });

        pri_cancel_btn.setText("Cancel");
        pri_cancel_btn.setToolTipText("");
        pri_cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pri_cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Prihod_TrošakLayout = new javax.swing.GroupLayout(Prihod_Trošak);
        Prihod_Trošak.setLayout(Prihod_TrošakLayout);
        Prihod_TrošakLayout.setHorizontalGroup(
            Prihod_TrošakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Prihod_TrošakLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(Prihod_TrošakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Prihod_TrošakLayout.createSequentialGroup()
                        .addComponent(pri_sort_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(pri_sort_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(pri_find_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pri_find_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pri_find_btn))
                    .addGroup(Prihod_TrošakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Prihod_TrošakLayout.createSequentialGroup()
                            .addComponent(pri_add_btn)
                            .addGap(18, 18, 18)
                            .addComponent(pri_delete_btn)
                            .addGap(11, 11, 11)
                            .addComponent(pri_save_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pri_cancel_btn))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        Prihod_TrošakLayout.setVerticalGroup(
            Prihod_TrošakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Prihod_TrošakLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(Prihod_TrošakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pri_sort_lbl)
                    .addComponent(pri_sort_cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pri_find_lbl)
                    .addComponent(pri_find_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pri_find_btn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Prihod_TrošakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pri_add_btn)
                    .addComponent(pri_delete_btn)
                    .addComponent(pri_cancel_btn)
                    .addComponent(pri_save_btn))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        Mansa.addTab("Prihod/Trošak", Prihod_Trošak);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Mansa, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(996, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Mansa, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(495, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void z_find_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z_find_btnActionPerformed

        String text = z_find_txt.getText();
        select(emp_tbl, text);
    }//GEN-LAST:event_z_find_btnActionPerformed

    private void z_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z_delete_btnActionPerformed
         ListSelectionModel select = emp_tbl.getSelectionModel();
        select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        select.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				
				idNumber = emp_tbl.getSelectedRow();
				}
		});
        if (idNumber == -1) {
            idNumber=0;
        }
        delete(emp_tbl.getAccessibleContext().getAccessibleName(), (emp_tbl.getValueAt(idNumber, 0)));
        zaposlenici();
    }//GEN-LAST:event_z_delete_btnActionPerformed

    private void V_Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_Add_btnActionPerformed
        insert(vozila_tbl.getAccessibleContext().getAccessibleName());
        vozila();
    }//GEN-LAST:event_V_Add_btnActionPerformed

    private void v_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_delete_btnActionPerformed
       //napraviti mogucnost odabira vise redaka i brisanje istih
         ListSelectionModel select = vozila_tbl.getSelectionModel();
        select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        select.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				
				idNumber = vozila_tbl.getSelectedRow();
				}
		});
        if (idNumber == -1) {
            idNumber=0;
        }
        delete(vozila_tbl.getAccessibleContext().getAccessibleName(), (vozila_tbl.getValueAt(idNumber, 0)));
        vozila();
    }//GEN-LAST:event_v_delete_btnActionPerformed

    private void V_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_save_btnActionPerformed
      
        ListSelectionModel select = vozila_tbl.getSelectionModel();
       
		select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		
		select.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				
				row = vozila_tbl.getSelectedRow();
                                column = vozila_tbl.getSelectedColumn();
				
				//update(vozila_tbl.getAccessibleContext().getAccessibleName(), (vozila_tbl.getValueAt(row, 0)), (vozila_tbl.getValueAt(row, column)), column);	
			}	
		});
                if(row>=0 && column>=0 && vozila_tbl.getValueAt(row, column)!= null && vozila_tbl.getValueAt(row, column)!= "")
                    update(vozila_tbl.getAccessibleContext().getAccessibleName(), (vozila_tbl.getValueAt(row, 0)), (vozila_tbl.getValueAt(row, column).toString()), (vozila_tbl.getColumnName(column)));
       //update(vozila_tbl, (vozila_tbl.getValueAt(row, column)), column);
       
    }//GEN-LAST:event_V_save_btnActionPerformed

    private void z_Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z_Add_btnActionPerformed
        insert(emp_tbl.getAccessibleContext().getAccessibleName());
        zaposlenici();
    }//GEN-LAST:event_z_Add_btnActionPerformed

    private void v_find_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_find_btnActionPerformed
        
        String text = v_find_txt.getText();
        select(vozila_tbl, text);
    }//GEN-LAST:event_v_find_btnActionPerformed

    private void z_Save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z_Save_btnActionPerformed
         ListSelectionModel select = emp_tbl.getSelectionModel();
       
		select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		
		select.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				
				row = emp_tbl.getSelectedRow();
                                column = emp_tbl.getSelectedColumn();
				System.out.println(column);
				//update(vozila_tbl.getAccessibleContext().getAccessibleName(), (vozila_tbl.getValueAt(row, 0)), (vozila_tbl.getValueAt(row, column)), column);	
			}	
		});
                if(row>=0 && column>=0 && emp_tbl.getValueAt(row, column)!= null)
                    update(emp_tbl.getAccessibleContext().getAccessibleName(), (emp_tbl.getValueAt(row, 0)), (emp_tbl.getValueAt(row, column).toString()), (emp_tbl.getColumnName(column)));
        
    }//GEN-LAST:event_z_Save_btnActionPerformed

    private void p_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_add_btnActionPerformed
       insert(projekti_tbl.getAccessibleContext().getAccessibleName());
       projekti();
    }//GEN-LAST:event_p_add_btnActionPerformed

    private void p_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_delete_btnActionPerformed
         ListSelectionModel select = projekti_tbl.getSelectionModel();
        select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        select.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				
				idNumber = projekti_tbl.getSelectedRow();
				}
		});
        if (idNumber == -1) {
            idNumber=0;
        }
        delete(projekti_tbl.getAccessibleContext().getAccessibleName(), (projekti_tbl.getValueAt(idNumber, 0)));
        projekti();
    }//GEN-LAST:event_p_delete_btnActionPerformed

    private void p_OK_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_OK_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_OK_btnActionPerformed

    private void p_find_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_find_btnActionPerformed
        String text = p_find_txt.getText();
        select(vozila_tbl, text);
    }//GEN-LAST:event_p_find_btnActionPerformed

    private void s_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_add_btnActionPerformed
        insert(skladiste_tbl.getAccessibleContext().getAccessibleName());
        skladiste();
    }//GEN-LAST:event_s_add_btnActionPerformed

    private void s_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_delete_btnActionPerformed
        ListSelectionModel select = skladiste_tbl.getSelectionModel();
        select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        select.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				
				idNumber = skladiste_tbl.getSelectedRow();
				}
		});
        if (idNumber == -1) {
            idNumber=0;
        }
        delete(skladiste_tbl.getAccessibleContext().getAccessibleName(), (skladiste_tbl.getValueAt(idNumber, 0)));
        skladiste();
    }//GEN-LAST:event_s_delete_btnActionPerformed

    private void s_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_save_btnActionPerformed
        ListSelectionModel select = skladiste_tbl.getSelectionModel();
       
		select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		
		select.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				
				row = skladiste_tbl.getSelectedRow();
                                column = skladiste_tbl.getSelectedColumn();
				
				}	
		});
                if(row>=0 && column>=0 && skladiste_tbl.getValueAt(row, column)!= null)
                    update(skladiste_tbl.getAccessibleContext().getAccessibleName(), (skladiste_tbl.getValueAt(row, 0)), (skladiste_tbl.getValueAt(row, column).toString()), (skladiste_tbl.getColumnName(column)));
      
    }//GEN-LAST:event_s_save_btnActionPerformed

    private void s_cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_cancel_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s_cancel_btnActionPerformed

    private void pri_add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pri_add_btnActionPerformed
        insert(prihod_trosak_tbl.getAccessibleContext().getAccessibleName());
        prihod_trosak();
    }//GEN-LAST:event_pri_add_btnActionPerformed

    private void pri_delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pri_delete_btnActionPerformed
       ListSelectionModel select = prihod_trosak_tbl.getSelectionModel();
        select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        select.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				
				idNumber = prihod_trosak_tbl.getSelectedRow();
				}
		});
        if (idNumber == -1) {
            idNumber=0;
        }
        delete(prihod_trosak_tbl.getAccessibleContext().getAccessibleName(), (prihod_trosak_tbl.getValueAt(idNumber, 0)));
        skladiste();
    }//GEN-LAST:event_pri_delete_btnActionPerformed

    private void pri_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pri_save_btnActionPerformed
        ListSelectionModel select = prihod_trosak_tbl.getSelectionModel();
       
		select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		
		select.addListSelectionListener(new ListSelectionListener() {
			public void valueChanged(ListSelectionEvent e) {
				
				row = prihod_trosak_tbl.getSelectedRow();
                                column = prihod_trosak_tbl.getSelectedColumn();
				
				}	
		});
                if(row>=0 && column>=0 && prihod_trosak_tbl.getValueAt(row, column)!= null)
                    update(prihod_trosak_tbl.getAccessibleContext().getAccessibleName(), (prihod_trosak_tbl.getValueAt(row, 0)), (prihod_trosak_tbl.getValueAt(row, column).toString()), (prihod_trosak_tbl.getColumnName(column)));
      
    }//GEN-LAST:event_pri_save_btnActionPerformed

    private void pri_cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pri_cancel_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pri_cancel_btnActionPerformed

    private void pri_find_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pri_find_btnActionPerformed
        String text = pri_find_txt.getText();
        select(prihod_trosak_tbl, text);
    }//GEN-LAST:event_pri_find_btnActionPerformed

    private void s_find_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_find_btnActionPerformed
        String text = s_find_txt.getText();
        select(skladiste_tbl, text);
    }//GEN-LAST:event_s_find_btnActionPerformed

    private void z_sort_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z_sort_cboxActionPerformed
        sortTable(z_sort_cbox, emp_tbl);
    }//GEN-LAST:event_z_sort_cboxActionPerformed

    private void v_sort_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_sort_cboxActionPerformed
        sortTable(v_sort_cbox, vozila_tbl);
    }//GEN-LAST:event_v_sort_cboxActionPerformed

    private void p_sort_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_sort_cboxActionPerformed
        sortTable(p_sort_cbox, projekti_tbl);
    }//GEN-LAST:event_p_sort_cboxActionPerformed

    private void s_sort_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_sort_cboxActionPerformed
        sortTable(s_sort_cbox, skladiste_tbl);
    }//GEN-LAST:event_s_sort_cboxActionPerformed

    private void pri_sort_cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pri_sort_cboxActionPerformed
        sortTable(pri_sort_cbox, prihod_trosak_tbl);  
    }//GEN-LAST:event_pri_sort_cboxActionPerformed

    private void emp_tblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emp_tblKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER && emp_tbl.isEditing()){         
         emp_tbl.setValueAt(emp_tbl.getCellEditor().getCellEditorValue(), emp_tbl.getEditingRow(),emp_tbl.getEditingColumn());
                    //if(emp_tbl.getModel().isCellEditable(i, j) && emp_tbl.getValueAt(i, j) != null)
                    update2(emp_tbl);
               }
          // TODO add your handling code here:
    }//GEN-LAST:event_emp_tblKeyPressed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MansardaGradnjaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MansardaGradnjaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MansardaGradnjaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MansardaGradnjaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
            new MansardaGradnjaView().setVisible(true);
            }
        });
       
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Mansa;
    private javax.swing.JPanel Prihod_Trošak;
    private javax.swing.JPanel Projekti;
    private javax.swing.JPanel Skladište;
    private javax.swing.JButton V_Add_btn;
    private javax.swing.JButton V_save_btn;
    private javax.swing.JPanel Vozila;
    private javax.swing.JPanel Zaposlenici;
    private javax.swing.JTable emp_tbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton p_OK_btn;
    private javax.swing.JButton p_add_btn;
    private javax.swing.JButton p_cancel_btn;
    private javax.swing.JButton p_delete_btn;
    private javax.swing.JButton p_find_btn;
    private javax.swing.JLabel p_find_lbl;
    private javax.swing.JTextField p_find_txt;
    private javax.swing.JComboBox<String> p_sort_cbox;
    private javax.swing.JLabel p_sort_lbl1;
    private javax.swing.JButton pri_add_btn;
    private javax.swing.JButton pri_cancel_btn;
    private javax.swing.JButton pri_delete_btn;
    private javax.swing.JButton pri_find_btn;
    private javax.swing.JLabel pri_find_lbl;
    private javax.swing.JTextField pri_find_txt;
    private javax.swing.JButton pri_save_btn;
    private javax.swing.JComboBox<String> pri_sort_cbox;
    private javax.swing.JLabel pri_sort_lbl;
    private javax.swing.JTable prihod_trosak_tbl;
    private javax.swing.JTable projekti_tbl;
    private javax.swing.JButton s_add_btn;
    private javax.swing.JButton s_cancel_btn;
    private javax.swing.JButton s_delete_btn;
    private javax.swing.JButton s_find_btn;
    private javax.swing.JLabel s_find_lbl;
    private javax.swing.JTextField s_find_txt;
    private javax.swing.JButton s_save_btn;
    private javax.swing.JComboBox<String> s_sort_cbox;
    private javax.swing.JLabel s_sort_lbl;
    private javax.swing.JTable skladiste_tbl;
    private javax.swing.JButton v_delete_btn;
    private javax.swing.JButton v_find_btn;
    private javax.swing.JLabel v_find_lbl;
    private javax.swing.JTextField v_find_txt;
    private javax.swing.JComboBox<String> v_sort_cbox;
    private javax.swing.JLabel v_sort_lbl;
    private javax.swing.JTable vozila_tbl;
    private javax.swing.JButton z_Add_btn;
    private javax.swing.JButton z_Save_btn;
    private javax.swing.JButton z_cancel_btn;
    private javax.swing.JButton z_delete_btn;
    private javax.swing.JButton z_find_btn;
    private javax.swing.JLabel z_find_lbl;
    private javax.swing.JTextField z_find_txt;
    private javax.swing.JComboBox<String> z_sort_cbox;
    private javax.swing.JLabel z_sort_lbl;
    // End of variables declaration//GEN-END:variables

    
    // crud metode
    public static void insert(String tableName){
     Mansarda mcon = new Mansarda();
        try {
           con = mcon.connectionMaker();
           PreparedStatement pstmt = con.prepareStatement("INSERT INTO "+ tableName +" () VALUES ()");
           pstmt.executeUpdate();
           
        } catch (SQLException ex) {
            Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void delete(String tablename, Object id){
        Mansarda mcon = new Mansarda();
        String red = id.toString();
        try {
           con = mcon.connectionMaker();
           PreparedStatement pstmt = con.prepareStatement("DELETE FROM "+tablename+" WHERE n_id = " + red);
           pstmt.executeUpdate();
           
        } catch (SQLException ex) {
            Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 
    public static void update(String tableName, Object i, String data, String colName){
        Mansarda mcon = new Mansarda();
        int id = Integer.parseInt(i.toString());
        try {
            con = mcon.connectionMaker();
            
            PreparedStatement pstmt = con.prepareStatement("UPDATE "+ tableName +" SET "+colName + " = '"+ data +"' WHERE n_id = "+ id);
            pstmt.executeUpdate();
        } catch (SQLException ex) {
             Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("UPDATE "+ tableName +" SET "+colName + " = '"+ data +"' WHERE n_id = "+ id);
    }
    
    public void update2(JTable table){
        Mansarda mcon = new Mansarda();
        
        
        try {
            con = mcon.connectionMaker();
            for(int i = 0; i < table.getRowCount();i++){
                for (int j = 0; j < table.getColumnCount(); j++) {
                    
                    if(table.getValueAt(i, j) != null){
                    PreparedStatement pstmt = con.prepareStatement("UPDATE "+ table.getAccessibleContext().getAccessibleName() +" SET "+table.getColumnName(j) + " = '"+ table.getValueAt(i, j) +"' WHERE n_id = "+ table.getValueAt(i, 0));
                    pstmt.executeUpdate();
                     System.out.println("UPDATE "+ table.getAccessibleContext().getAccessibleName() +" SET "+table.getColumnName(j) + " = '"+ table.getValueAt(i, j) +"' WHERE n_id = "+ table.getValueAt(i, 0));
                
                }}
            }
            
        } catch (SQLException ex) {
             Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }
    
    public static void select(JTable table, String data){
        Mansarda mcon = new Mansarda();
        con = mcon.connectionMaker();
        
        String tableName = table.getAccessibleContext().getAccessibleName();
        int col = table.getColumnCount();
        String sqlquery = "SELECT * FROM "+ tableName +" Where";
        
        for(int i = 0;i<=(col-1);i++) {
            if((i+1)<col){
                sqlquery = sqlquery +" ("+ table.getColumnName(i) + " LIKE '%" +data+ "%') OR";
                //sqlquery = sqlquery +"("+ table.getColumnName(i) + " LIKE '%"+data+"%')";
            }else{
            //sqlquery = sqlquery +"("+ table.getColumnName(i) + " LIKE '%"+data+"%') OR";
            sqlquery = sqlquery +" ("+ table.getColumnName(i) + " LIKE '%" +data+ "%')";
        }}
        System.out.println(sqlquery);
        Statement stmt;
        ResultSet rs;
        try {
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery(sqlquery);
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //tablice i viewovi
    private void vozila() {
        Mansarda mcon = new Mansarda();
        con = mcon.connectionMaker();
        sqlquery = "SELECT * FROM " + vozila_tbl.getAccessibleContext().getAccessibleName();
        Statement stmt;
        ResultSet rs;
        try {
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery(sqlquery);
            vozila_tbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillCbox(vozila_tbl, v_sort_cbox);
    }

    private void zaposlenici() {
        Mansarda mcon = new Mansarda();
        con = mcon.connectionMaker();
        
        sqlquery = "SELECT * FROM " + emp_tbl.getAccessibleContext().getAccessibleName();
        Statement stmt;
        ResultSet rs;
        try {
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery(sqlquery);
            emp_tbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillCbox(emp_tbl, z_sort_cbox);
    }

    private void projekti() {
        Mansarda mcon = new Mansarda();
        con = mcon.connectionMaker();
        
        sqlquery = "SELECT * FROM " + projekti_tbl.getAccessibleContext().getAccessibleName();
        Statement stmt;
        ResultSet rs;
        try {
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery(sqlquery);
            projekti_tbl.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillCbox(projekti_tbl, p_sort_cbox);
    }

    private void skladiste() {
        Mansarda mcon = new Mansarda();
        con = mcon.connectionMaker();
        
        sqlquery = "SELECT * FROM " + skladiste_tbl.getAccessibleContext().getAccessibleName();
        Statement stmt;
        ResultSet rs;
        try {
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery(sqlquery);
            skladiste_tbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillCbox(skladiste_tbl, s_sort_cbox);
    }

    private void prihod_trosak() {
        Mansarda mcon = new Mansarda();
        con = mcon.connectionMaker();
        
        sqlquery = "SELECT * FROM " + prihod_trosak_tbl.getAccessibleContext().getAccessibleName();
        Statement stmt;
        ResultSet rs;
        try {
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery(sqlquery);
            prihod_trosak_tbl.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
        fillCbox(prihod_trosak_tbl, pri_sort_cbox);
    }
    
    // comboboxes
    
    private void fillCbox(JTable table, JComboBox box){
        String header ;
        for(int i = 0; i<table.getColumnCount();i++){
            header = table.getColumnName(i);
            box.addItem(header);
        }
        
    }
    private void sortTable(JComboBox box, JTable table){
         Mansarda mcon = new Mansarda();
        con = mcon.connectionMaker();
        
        sqlquery = "SELECT * FROM " + table.getAccessibleContext().getAccessibleName()+ " ORDER BY "+ (String) box.getSelectedItem() + " ASC";
        Statement stmt;
        ResultSet rs;
        try {
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stmt.executeQuery(sqlquery);
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(MansardaGradnjaView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
