//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.06 at 12:55:39 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.siemens.hr/cvc/labsensors/configuration/sensorConfiguration", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hr.siemens.cvc.labsensors.configuration.sensorConfiguration;
